#!/bin/bash
set -eu

RABBITMQ_CLUSTER_NAME=${1:-First parameter is the cluster name}
echo "Starting RabbitMQ server $RABBITMQ_CLUSTER_NAME"

helm install --name $RABBITMQ_CLUSTER_NAME \
  --set rabbitmq.username=admin,rabbitmq.password=admin \
  -f conf/rabbitmq-helm-values.yaml \
  stable/rabbitmq
