#!/usr/bin/env bash

set -x
set -e
set -o pipefail

CHURNER=${1:?first parameter is the name of this churner. Used to name queues}
TIMES=${2:-"1"}
DURATION=${3:-"10"}

. setup

queue_churner() {

  QUEUE_PREFIX=${1:?first parameter is the queue prefix name}
  QUEUES=${2:?first parameter is the number of queues}
  DURATION=${3:?third parameter is the duration of this queue churner}

  URIS="$(./_uri $HOSTNAMES)"

  echo "Perftest with uri $URIS"

  perftest   \
--autoack \
--size 100 \
--routing-key perf-test \
--uris $URIS \
--queue-pattern $QUEUE_PREFIX \
--queue-pattern-from 1 \
--queue-pattern-to ${QUEUES:?must be set} \
--consumers ${QUEUES:?must be set} \
--producers ${QUEUES:?must be set} \
--time ${DURATION}  1>/dev/null

}

printf "%s\n" "" \
	"## Queue Churner $CHURNER iagainst $HOSTNAMES " \

for i in $(seq 1 $TIMES); do
  printf "Launching Queue Churner #%s-%s " $CHURNER $i
  queue_churner "$CHURNER-%d" 10 $DURATION
done
