#!/usr/bin/env bash

set -e
set -o pipefail

CHURNER=${1:?first parameter is the name of this churner. Used to name queues}
QUEUES=${2:-"10"}
TIMES=${3:-"1"}
MIN_DURATION=${4:-"5"}
MAX_DURATION=${5:-"10"}

. setup

queue_churner() {

  QUEUE_PREFIX=${1:?first parameter is the queue prefix name}
  QUEUES=${2:?first parameter is the number of queues}
  DURATION=${3:?third parameter is the duration of this queue churner}

	# PerfTest is not able yet to handle the situation when it fails to establish the first
	# connection. With this while-loop we randomly choose one node from the list of nodes
	# until it successfully connects
	while : ; do
	    URI="$(./_uri $HOSTNAMES | tr ',' "\n"|shuf|head -n 1)"
	    echo "Perftest with uri $URIS"

	    perftest   \
	--autoack \
	--size 100 \
	--routing-key perf-test \
	--uris $URI \
	--queue-pattern $QUEUE_PREFIX \
	--queue-pattern-from 1 \
	--queue-pattern-to ${QUEUES:?must be set} \
	--consumers ${QUEUES:?must be set} \
	--producers ${QUEUES:?must be set} \
	--time ${DURATION}  1>/dev/null

	   [ $? = 1 ] || break
		 echo "Unable to connect to $URI. Trying in 1 second"
	   sleep 1
	 done
}

printf "%s\n" "" \
	"## Queue Churner $CHURNER iagainst $HOSTNAMES " \

for i in $(seq 1 $TIMES); do
  printf "Launching Queue Churner #%s-%s " $CHURNER $i
	DURATION=$(( $RANDOM % $MAX_DURATION + $MIN_DURATION));
  queue_churner "$CHURNER-%d" $QUEUES $DURATION
done
