#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function kill_connections {
  $SCRIPT/list-conn | grep "$1" | awk -F '\t' '{print $1}' | while read line; do
    connection=`$SCRIPT/rawurlencode "$line"`
    echo "Killing connection $line"
    curl -s -X DELETE -u guest:guest localhost:${PORT:-15673}/api/connections/$connection
  done
}
function check_queue_depth {
  depth=`curl -s -u guest:guest localhost:${PORT:-15673}/api/queues/%2F/$1 | jq .messages_ready`
  echo "There are $depth messages in the $1 queue"
}

check_queue_depth trades.trade-logger
kill_connections
