#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

curl -s -u guest:guest localhost:${PORT:-15673}/api/connections | jq -r '.[]| [.name,.user_provided_name,.user,.node]|@tsv'
