#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function get_queue_depth {
  curl -u guest:guest localhost:${PORT:-15672}/api/queues | jq '.[] | {name,messages_ready} '
}

function kill_all_connections {
  curl -u guest:guest localhost:${PORT:-15672}/api/queues | jq '.[] | {name,messages_ready} '
}

get_queue_depth
