#!/usr/bin/env bash

SCRIPT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPT/check-commands

function kill_connections {
  $SCRIPT/list-conn | grep "$1" | awk -F '\t' '{print $1}' | while read line; do
    connection=`$SCRIPT/../docker/rawurlencode "$line"`
    echo "Killing connection $line"
    curl -s -X DELETE ${RABBIT_URL}connections/$connection
  done
}

curl-installed
RABBIT_URL=$(ensure-chaos-service-key $RABBIT)

kill_connections $1
