#!/usr/bin/env bash

set -e
set -o pipefail

export TOTAL_RATE="${RATE:-10000}"

printf "%s\n" "" \
	"## How do multiple queues affect message latency?" \
	"" \
	"### Publish rate: $RATE msg/s" \
	"" \
	"| Queues<br /> Producers<br /> Consumers | Msg/s per queue | Max 99th | Max 95th | Max 75th |" \
	"| -: | -: | -: | -: | -: |"

unset QUEUES
for QUEUES in 1 2 5 10 100; do
  PRODUCERS=$QUEUES
  RATE=$((TOTAL_RATE/PRODUCERS))
  CONSUMERS=$QUEUES
  printf "| %s | %s " $QUEUES $RATE
  . _run_perf_test
  . _max_message_latency_quantiles
done
