#!/usr/bin/env bash

set -e
set -o pipefail

export RATE=${RATE:-10000}

printf "%s\n" "" \
	"## What are the effects of queue mirroring?" \
	"" \
	"Publish rate: $RATE msg/s" \
	"| Queue mirrors | Max 99th | Max 95th | Max 75th |" \
	"| -:        | -:       | -:       | -:       |"

printf "| %s " 1
${PERFTEST_PATH:?must be set}/bin/runjava com.rabbitmq.perf.PerfTest \
--autoack \
--predeclared \
--queue 1m \
--interval 15 \
--size 1000 \
--routing-key 1m \
--uri "amqp://admin:${RABBITMQ_PASS:?must be set}@${RABBITMQ_HOST:?must be set}:5672/%2F" \
--metrics-prometheus \
--metrics-tags 'type=publisher,type=consumer,deployment=low-latency' \
--consumers ${CONSUMERS:?must be set} \
--producers ${PRODUCERS:?must be set} \
--rate ${RATE:?must be set} \
--time ${TEST_DURATION:?must be set} $@ 1>/dev/null
. _max_message_latency_quantiles

printf "| %s " 2
${PERFTEST_PATH:?must be set}/bin/runjava com.rabbitmq.perf.PerfTest \
--autoack \
--predeclared \
--queue 2m \
--interval 15 \
--size 1000 \
--routing-key 2m \
--uri "amqp://admin:${RABBITMQ_PASS:?must be set}@${RABBITMQ_HOST:?must be set}:5672/%2F" \
--metrics-prometheus \
--metrics-tags 'type=publisher,type=consumer,deployment=low-latency' \
--consumers ${CONSUMERS:?must be set} \
--producers ${PRODUCERS:?must be set} \
--rate ${RATE:?must be set} \
--time ${TEST_DURATION:?must be set} $@ 1>/dev/null
. _max_message_latency_quantiles

printf "| %s " 3
${PERFTEST_PATH:?must be set}/bin/runjava com.rabbitmq.perf.PerfTest \
--autoack \
--predeclared \
--queue 3m \
--interval 15 \
--size 1000 \
--routing-key 3m \
--uri "amqp://admin:${RABBITMQ_PASS:?must be set}@${RABBITMQ_HOST:?must be set}:5672/%2F" \
--metrics-prometheus \
--metrics-tags 'type=publisher,type=consumer,deployment=low-latency' \
--consumers ${CONSUMERS:?must be set} \
--producers ${PRODUCERS:?must be set} \
--rate ${RATE:?must be set} \
--time ${TEST_DURATION:?must be set} $@ 1>/dev/null
. _max_message_latency_quantiles

